// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nft_project.Data;

#nullable disable

namespace nft_project.Migrations.CampaignDB
{
    [DbContext(typeof(CampaignDBContext))]
    partial class CampaignDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("nft_project.Models.Campaign", b =>
                {
                    b.Property<string>("camp_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("desciption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("img1_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img2_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("camp_id");

                    b.ToTable("Campaign");
                });
#pragma warning restore 612, 618
        }
    }
}
